- openedxscorm/scormxblock.py
We are facing the following error because files are uploaded to Google Storage
```
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 1037, in handle
results = handler(request, suffix)
File "/edx/app/edxapp/venvs/edxapp/src/openedxscorm/openedxscorm/scormxblock.py", line 223, in studio_submit
self.extract_package(package_file)
File "/edx/app/edxapp/venvs/edxapp/src/openedxscorm/openedxscorm/scormxblock.py", line 280, in extract_package
dest_path, scorm_zipfile.open(zipinfo.filename),
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/files/storage.py", line 54, in save
return self._save(name, content)
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/storages/backends/gcloud.py", line 159, in _save …
```
> Avoid file seek when saving extracted files

- openedxscorm/static/html/studio.html
There is a problem with scorm weight displaying in settings from studio. To reproduce it we need to open xblock settings menu, change the weight value from default to new arbitrary one and save changes. After opening this menu again the displayed weight value is empty. The reason is localization. For the tested locale the float weight value is represented with ',' instead of '.', but it is incorrect value for input tag's `value` attribute, so nothing is displayed. To fix it, `unlocalize` filter is applied to scorm_xblock.weight value.
> fix: Problem with weight displaying related to localization is fixed

- openedxscorm/static/js/src/scormxblock.js
uncachedValues is an Array not Object so element membership needs to use Array.includes()
Fixes #30
> Fix getValue, processSetValueQueueItems uncachedValues check

- README.rst
- openedxscorm/scormxblock.py
- openedxscorm/storage.py
- setup.py
**Summary:**
Implement a custom storage solution to store and retrieve data from a private S3 bucket. Modify the handling of SCORM content requests loaded via JavaScript from a primary file, ensuring they are routed through a custom XBlock view instead of directly accessing the S3 storage. All SCORM XBlock resource requests should be intercepted by the custom view to add signatures before forwarding them to the S3 storage, allowing secure access to private content. Additionally, the ability to read SCORM content from a private bucket should be configurable via Django settings.
**Changes Made:**
- Created a custom storage implementation to facilitate data storage in a private S3 bucket.
- Implemented a custom XBlock view to handle SCORM content requests.
- Modified the routing of SCORM …
> Custom storage for SCORM Xblock

- openedxscorm/scormxblock.py
`requests` is imported but never used. It has been replaced by `urllib.request.urlopen`
> remove unused import

- openedxscorm/static/js/src/scormxblock.js
This PR has changes to fix a js error which causes failure to load SCORM content in LMS when multiple SCORM blocks are added in single unit and unit is access by learner. In case of Staff users this error does not popup. Changes in this PR stop initializing student search autocomplete in case of learners since learners don't need to view reports. 
JS Error from browser's console
```
properties of undefined (reading 'nodeType')
at acceptData (lms-main_vendor.211c5a13e466.js:2:16678)
at Data.cache (lms-main_vendor.211c5a13e466.js:2:17059)
at Data.set (lms-main_vendor.211c5a13e466.js:2:17350)
at Data.access (lms-main_vendor.211c5a13e466.js:2:17795)
at Function.data (lms-main_vendor.211c5a13e466.js:2:19140)
at e.<computed>.<computed>._createWidget (lms-main_vendor.211c5a13e466.js:11:17721)
at …
```
> fix: avoid initializing student search autocomplete if reports are not needed

- openedxscorm/storage.py
This PR has couple of changes to
1. Remove unused import
2. Rename `bucket` param in S3Boto3Storage constructor to `bucket_name` since it is removed since [1.10](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#s3-8). This change does not break anything in older(1.9) version of django-storages.
> refactor: remove unused import and rename S3Boto3Storage constructor param

- README.rst
Explain that the v16 version is meant for Palm, and enumerate the
version numbers corresponding to recent Open edX releases.
Fixes #35.
> docs: Update README for recent Open edX versions

- openedxscorm/scormxblock.py
Since '%' is a special character in gettext, to use in default
message it has be to escaped, otherwise gettext would get the
default strings in the templates.
> fix: escape the '%' in gettext

- openedxscorm/scormxblock.py
- openedxscorm/static/css/scormxblock.css
- openedxscorm/static/html/scormxblock.html
- openedxscorm/static/html/studio.html
- openedxscorm/static/js/src/scormxblock.js
- openedxscorm/static/js/src/studio.js
Fixes #53.
**Changes**
- Added an option to enable navigation menu on the left side of the scorm panel.
- Navigation menu is built using the title tags of the items in the `imsmanifest.xml` file.
- Leaf item tags are also clickable in the navigation menu which change the current page to the clicked page.
- Added an option to specify width of navigation menu. Default size is 30% of scorm panel width, 70% is assigned to the course iframe.
- Added a `navigationClick` check on `GetValue` scorm API call as Chromium blocked synchronous calls on page unload and we didn't want to make an API call when changing pages using the navigation menu.
> feat: add left navigation menu for course

- openedxscorm/scormxblock.py
Some packages may send the final score after updating success and/or completion status
Fix Issue #56
> Publish a grade on new score even after completed

- openedxscorm/scormxblock.py
cmi.score.scaled in SCORM 2004 packages should be a
decimal between 0 and 1 reflecting a percentage score
(Actually cmi.score.scaled can have -1 to 1 but Open edX
shouldn't allow negative scores)
Fix Issue #55
> get_ and set_value handle cmi.score.scaled

- openedxscorm/scormxblock.py
This PR has these changes  
- add querystring to S3 signed url if it is present in the proxy request. This might help in fixing #60
- unqoute scorm page url to allow scorm when package is saved in local file system. This issue is mentioned in #60 too
> fix: Add querystring to S3 signed url if it is present in the proxy request

- .github/workflows/auto-add-to-project.yml
- README.rst
- openedxscorm/scormxblock.py
- openedxscorm/storage.py
- openedxscorm/tests.py
This will introduce some clean-ups:
- Python & Yaml code highlight added in docs
- clean up readme for better readability
- Python code reformatted with black and isort
- f-strings used for better readability
Also, fixes the "Add to project on pull request" failing job
> chore: cleanup

- openedxscorm/scormxblock.py
Removed `pkg_resources` for compatibility with newer python versions as discussed in this [issue](https://github.com/overhangio/tutor/issues/966).
Ensured that this xblock is working with python `3.12` & `3.8` as mentioned in this [issue](https://github.com/overhangio/openedx-scorm-xblock/issues/67).
> Replace deprecated pkg_resources package with importlib_resources

- README.rst
- openedxscorm/scormxblock.py
- openedxscorm/static/js/src/scormxblock.js
- openedxscorm/tests.py
After this [change](https://github.com/edly-io/openedx-scorm-xblock/commit/8fe1614648e453f47ab22da92438dda890448fc6), `scorm_get_values` was exclusively used for getting `uncached_values`.
This commit: 
- removes student information and other scorm data from get value func and sends it as part of scorm_data in student view,
- adds `cmi.score.scaled` to `uncached_values`,
- and removes old test cases.
> Improve GetValue API 

- changelog.d/20240621_201400_zia.fazal_fix_backward_compat.md
- openedxscorm/scormxblock.py
These changes pass complete path of the index file because  storage.exists expects a file path when storage is set to S3. This should fix issue #76
> fix: S3 storage exists always return false for directories

- openedxscorm/scormxblock.py
Some of my Scorm files (client's courses) are not being uploaded because, during extraction, some of the filenames are ending with `\\` double backslash. But, the code ignores only the filenames ending with `/` forward slash.
> fix: Scorm file upload error

- .github/workflows/publish_pypi.yml
closes #82
** Changes **
- Upgraded ubuntu-20.04 to ubuntu-latest.
- Upgraded from python 3.8 to python 3.12.
- Upgrade checkout and setup-python versions.
- Remove tokens as repository is now already added as a trusted publisher on pypi.
> ci: upgrade publish_pypi to ubuntu-latest and python 3.12

- openedxscorm/scormxblock.py
I believe this was originally written to serve redirects in https://github.com/overhangio/openedx-scorm-xblock/pull/29 but before merge it was changed to proxy the contents.
> docs: Correct docstring for assets_proxy

- openedxscorm/scormxblock.py
- openedxscorm/static/html/scormxblock.html
- openedxscorm/static/html/studio.html
- openedxscorm/static/js/src/studio.js
Some components by default has its own button for full screen functionality. So, the full screen button could be optional where instructors would be able to turn that on or off.
> feat: Add option to turn on or off fullscreen button in SCORM content

- openedxscorm/scormxblock.py
Scorm Xblock was failing in nightly due to importlib_resources being removed. This has been done for backwards compatibility.
Reference PR: https://github.com/edly-io/h5pxblock/pull/42
> fix: 'openedxscorm.scormxblock' is not a package

- README.rst
- openedxscorm/scormxblock.py
- openedxscorm/storage.py
Closes #87
- We do this so that custom storage does not need to be defined for Scorm
- The default storage configured for Open edX should work out of the box with scorm now
- This also fixes an issue of X-Frame-Options on the LMS when running in development mode
> feat: generalize proxy assets for use with every storage

- openedxscorm/scormxblock.py
- openedxscorm/static/js/src/scormxblock.js
> Full screen navigation is very hard to navigate and makes it impossible for users to scroll down completely and access the content. It completely hides the buttons making it impossible to move forward. They have to exit full screen to continue to navigate.
>
> Happens only on certain devices (like a laptop), does not happen as often at higher resolutions.
The solution would be to have the height of `<div class="scorm-pane " />` updated to the screen height if it is less than the saved height.
This PR resolved #92
> fix: fullscreen page height

- changelog.d/20250203_142818_danyal.faheem_HEAD.md
- openedxscorm/static/js/src/scormxblock.js
fixes #96.
The scorm panel would retain any custom height set or the default 450px height in fullscreen mode thus defeating the purpose of the fullscreen mode.
We now cover the entire display in fullscreen mode.
> fix: make scorm panel cover entire height in fullscreen mode

- README.rst
- changelog.d/20250307_193543_danyal.faheem.md
- openedxscorm/scormxblock.py
fixes #99.
A change was introduced in #91 where instead of accessing the url method on the storage backend, we would proxy the assets through the LMS. This was done to generalize the backend and allow for it to work out of the box with external storages such as S3.
However, as pointed out in #99, this can lead to some degraded performance as compared to just accessing scorm files directly from an external storage. Hence, we provide an option to change this behaviour and it is up to the user to choose them.
The default option will be proxying through the LMS as it does not require any extra setup. 
An important concept necessary here is that the `url` method must be defined on the storage if the `DEFAULT_STORAGE_URL` option is set to true.
> perf: provide option to query asset using storage default url or through the LMS
